defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      theme: jekyll-theme-minimal
      title: smcnally's home @ github
      description: recipes, workflows, code and work in-progress